name: "Build NixOS Configuration"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Set up Cachix
        uses: cachix/cachix-action@v15
        with:
          name: ${{ vars.CACHIX_NAME }}
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build NixOS system
        # ⭐️ ADD THIS LINE ⭐️
        # This tells the step to run inside your 'nixos' subfolder
        working-directory: nixos
        run: nix build .#nixosConfigurations.zephyrus-m16.config.system.build.toplevel